[broker]
address = "localhost:9092"
security_protocol = ""
sasl_mechanism = "PLAIN"
sasl_username = "username"
sasl_password = "password"
topic = "ccx.ocp.results"
payload_tracker_topic = "platform.payload-status"
dead_letter_queue_topic = "dead.letter.queue"
service_name = "insights-results-aggregator"
group = "aggregator"
enabled = true
enable_org_allowlist = false

[server]
address = ":8080"
api_prefix = "/api/v1/"
api_spec_file = "openapi.json"
debug = true
auth = true
auth_type = "xrh"
maximum_feedback_message_length = 255
org_overview_limit_hours = 2

[processing]
org_allowlist_file = "org_allowlist.csv"

[storage]
db_driver = "postgres"
pg_username = "wrong-one"
pg_password = "wrong-one"
pg_host = "wrong-one"
pg_port = 5432
pg_db_name = "wrong-one"
pg_params = "sslmode=disable"
log_sql_queries = true
type = "sql"

[content]
path = "/rules-content"

[logging]
debug = false
log_level = ""
logging_to_cloud_watch_enabled = false

[cloudwatch]
aws_access_id = "a key id"
aws_secret_key = "tshhhh it is a secret"
aws_session_token = ""
aws_region = "us-east-1"
log_group = "platform-dev"
stream_name = "insights-results-aggregator"
debug = false
create_stream_if_not_exists = false

[metrics]
namespace = "aggregator"
