DROP TABLE IF EXISTS migration_info;
DROP TABLE IF EXISTS cluster_rule_toggle;
DROP TABLE IF EXISTS cluster_rule_user_feedback;
DROP TABLE IF EXISTS cluster_user_rule_disable_feedback;
DROP TABLE IF EXISTS report;
DROP TABLE IF EXISTS rule_error_key;
DROP TABLE IF EXISTS rule;
DROP TABLE IF EXISTS rule_hit;
DROP TABLE IF EXISTS advisor_ratings;
DROP TABLE IF EXISTS consumer_error;
DROP TABLE IF EXISTS recommendation;
DROP TABLE IF EXISTS report_info;
DROP TABLE IF EXISTS rule_disable;
DROP SCHEMA IF EXISTS dvo CASCADE;