name: Pytest

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  scenarios-lists-updated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - name: Scenarios list check
        run: make doc-check
